# -*- coding: utf-8 -*-
"""LAB10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKeJL6ogiwH7v7LFlH83jCgVnivOmcVQ
"""

# ================================
# IMPORT LIBRARIES
# ================================
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.layers import Layer, MultiHeadAttention, LayerNormalization

# ================================
# DATASET
# ================================
data = """artificial intelligence systems learn patterns from data.
sequence models process information step by step.
recurrent neural networks are useful for sequence prediction.
lstm networks handle long term dependencies.

deep learning models improve sequence learning.
generative models create new samples from learned patterns.
language models predict the next word in a sentence.
sequence generation is used in chatbots and assistants.

machine learning helps computers learn automatically.
training data improves model accuracy.
neural networks simulate human brain structures.
optimization algorithms improve learning efficiency.

technology is transforming modern education.
online learning platforms use artificial intelligence.
students benefit from intelligent tutoring systems.
automation improves productivity and decision making."""

# ================================
# TOKENIZATION
# ================================
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])

total_words = len(tokenizer.word_index) + 1

# ================================
# CREATE SEQUENCES
# ================================
input_sequences = []

for line in data.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram_seq = token_list[:i+1]
        input_sequences.append(n_gram_seq)

max_len = max(len(x) for x in input_sequences)

input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')

X = input_sequences[:, :-1]
y = input_sequences[:, -1]

y = tf.keras.utils.to_categorical(y, num_classes=total_words)

# ================================
# LSTM MODEL
# ================================
lstm_model = Sequential([
    Embedding(total_words, 64, input_length=max_len-1),
    LSTM(100),
    Dense(total_words, activation='softmax')
])

lstm_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print("Training LSTM Model...")
lstm_model.fit(X, y, epochs=200, verbose=1)

# ================================
# LSTM TEXT GENERATION
# ================================
def generate_text_lstm(seed_text, next_words=10):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')

        predicted = np.argmax(lstm_model.predict(token_list), axis=-1)

        for word, index in tokenizer.word_index.items():
            if index == predicted:
                seed_text += " " + word
                break

    return seed_text

print("\nLSTM Output:")
print(generate_text_lstm("artificial intelligence", 10))

# ================================
# POSITIONAL ENCODING
# ================================
class PositionalEncoding(Layer):
    def __init__(self, max_len, d_model):
        super().__init__()

        pos = np.arange(max_len)[:, np.newaxis]
        i = np.arange(d_model)[np.newaxis, :]

        angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
        angle_rads = pos * angle_rates

        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])

        self.pos_encoding = tf.cast(angle_rads[np.newaxis, ...], dtype=tf.float32)

    def call(self, inputs):
        return inputs + self.pos_encoding[:, :tf.shape(inputs)[1], :]

# ================================
# TRANSFORMER MODEL
# ================================
def build_transformer(vocab_size, max_len):
    inputs = tf.keras.Input(shape=(max_len-1,))

    x = Embedding(vocab_size, 64)(inputs)
    x = PositionalEncoding(max_len, 64)(x)

    attn = MultiHeadAttention(num_heads=2, key_dim=64)(x, x)
    x = LayerNormalization()(x + attn)

    ffn = Dense(128, activation='relu')(x)
    ffn = Dense(64)(ffn)
    x = LayerNormalization()(x + ffn)

    x = tf.keras.layers.GlobalAveragePooling1D()(x)
    outputs = Dense(vocab_size, activation='softmax')(x)

    model = tf.keras.Model(inputs, outputs)
    return model

transformer_model = build_transformer(total_words, max_len)
transformer_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print("\nTraining Transformer Model...")
transformer_model.fit(X, y, epochs=200, verbose=1)

# ================================
# TRANSFORMER TEXT GENERATION
# ================================
def generate_text_transformer(seed_text, next_words=10):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')

        predicted = np.argmax(transformer_model.predict(token_list), axis=-1)

        for word, index in tokenizer.word_index.items():
            if index == predicted:
                seed_text += " " + word
                break

    return seed_text

print("\nTransformer Output:")
print(generate_text_transformer("machine learning", 10))