# -*- coding: utf-8 -*-
"""LAB12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKeJL6ogiwH7v7LFlH83jCgVnivOmcVQ
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
import re

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ================= DATA =================
pairs = [
    ("hello", "hi how are you"),
    ("how are you", "i am fine"),
    ("what is your name", "i am a chatbot"),
    ("where do you live", "i live on the internet"),
    ("bye", "goodbye")
]

# ================= PREPROCESS =================
def clean(text):
    text = text.lower()
    text = re.sub(r"[^a-z ]", "", text)
    return text

pairs = [(clean(x), clean(y)) for x, y in pairs]

# ================= VOCAB =================
words = []
for x, y in pairs:
    words += x.split()
    words += y.split()

vocab = ["<pad>", "<sos>", "<eos>"] + list(set(words))
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for w, i in word2idx.items()}

def encode(sentence):
    return [word2idx[w] for w in sentence.split()]

def decode(indices):
    return " ".join([idx2word[i] for i in indices])

# ================= DATASET =================
data = []
for x, y in pairs:
    inp = encode(x)
    out = [word2idx["<sos>"]] + encode(y) + [word2idx["<eos>"]]
    data.append((inp, out))

# ================= MODEL =================
class Encoder(nn.Module):
    def __init__(self, vocab_size, emb_size, hidden_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, emb_size)
        self.lstm = nn.LSTM(emb_size, hidden_size, batch_first=True)

    def forward(self, x):
        emb = self.embedding(x)
        outputs, (h, c) = self.lstm(emb)
        return outputs, (h, c)

class Attention(nn.Module):
    def __init__(self, hidden_size):
        super().__init__()
        self.attn = nn.Linear(hidden_size * 2, hidden_size)
        self.v = nn.Linear(hidden_size, 1, bias=False)

    def forward(self, hidden, encoder_outputs):
        seq_len = encoder_outputs.size(1)
        hidden = hidden.repeat(seq_len, 1, 1).permute(1, 0, 2)
        energy = torch.tanh(self.attn(torch.cat((hidden, encoder_outputs), dim=2)))
        attention = self.v(energy).squeeze(2)
        return torch.softmax(attention, dim=1)

class Decoder(nn.Module):
    def __init__(self, vocab_size, emb_size, hidden_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, emb_size)
        self.lstm = nn.LSTM(hidden_size + emb_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size * 2, vocab_size)
        self.attn = Attention(hidden_size)

    def forward(self, x, hidden, encoder_outputs):
        x = x.unsqueeze(1)
        emb = self.embedding(x)

        attn_weights = self.attn(hidden[0], encoder_outputs)
        context = torch.bmm(attn_weights.unsqueeze(1), encoder_outputs)

        lstm_input = torch.cat((emb, context), dim=2)
        output, hidden = self.lstm(lstm_input, hidden)

        output = torch.cat((output.squeeze(1), context.squeeze(1)), dim=1)
        output = self.fc(output)

        return output, hidden, attn_weights

# ================= INIT =================
vocab_size = len(vocab)
emb_size = 64
hidden_size = 128

encoder = Encoder(vocab_size, emb_size, hidden_size).to(device)
decoder = Decoder(vocab_size, emb_size, hidden_size).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(list(encoder.parameters()) + list(decoder.parameters()), lr=0.01)

# ================= TRAIN =================
epochs = 300

for epoch in range(epochs):
    total_loss = 0

    for inp, out in data:
        inp_tensor = torch.tensor(inp).unsqueeze(0).to(device)
        out_tensor = torch.tensor(out).to(device)

        optimizer.zero_grad()

        encoder_outputs, hidden = encoder(inp_tensor)

        decoder_input = torch.tensor([word2idx["<sos>"]]).to(device)
        loss = 0

        for t in range(1, len(out_tensor)):
            output, hidden, _ = decoder(decoder_input, hidden, encoder_outputs)
            loss += criterion(output, out_tensor[t].unsqueeze(0))
            decoder_input = out_tensor[t].unsqueeze(0) # Fix: unsqueeze to maintain batch dimension

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {total_loss:.4f}")

# ================= INFERENCE =================
def reply(sentence):
    sentence = clean(sentence)
    inp = torch.tensor(encode(sentence)).unsqueeze(0).to(device)

    encoder_outputs, hidden = encoder(inp)

    decoder_input = torch.tensor([word2idx["<sos>"]]).to(device)
    result = []

    for _ in range(10):
        output, hidden, attn = decoder(decoder_input, hidden, encoder_outputs)
        pred = output.argmax(1).item()

        if idx2word[pred] == "<eos>":
            break

        result.append(idx2word[pred])
        decoder_input = torch.tensor([pred]).to(device)

    return " ".join(result)

# ================= TEST =================
print("\n=== TEST ===")
print("Input: how are you")
print("Output:", reply("how are you"))

print("\nInput: hello")
print("Output:", reply("hello"))