# -*- coding: utf-8 -*-
"""LAB9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKeJL6ogiwH7v7LFlH83jCgVnivOmcVQ
"""

# ===============================
# 🔹 IMPORTS
# ===============================
import numpy as np
import tensorflow as tf
import torch
import torch.nn as nn

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# ===============================
# 🔹 DATASET
# ===============================
data = """machine learning models learn patterns from data.
sequence models process data step by step.
recurrent neural networks are designed for sequential tasks.
rnn models maintain hidden states across time steps.

long short term memory networks solve long dependency problems.
lstm uses gates to control information flow.
gru models simplify the lstm architecture.
sequence prediction is useful in many applications.

language modeling predicts the next word in a sentence.
speech recognition processes audio sequences.
time series forecasting predicts future values.
music generation creates new melodies.

generative models learn probability distributions.
they generate new samples similar to training data.
sequence generation is widely used in artificial intelligence.
deep learning improves sequence modeling performance."""

# ===============================
# 🔹 PART 1: LSTM MODEL
# ===============================

# Tokenization
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
total_words = len(tokenizer.word_index) + 1

# Create sequences
input_sequences = []
for line in data.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        input_sequences.append(token_list[:i+1])

# Padding
max_seq_len = max(len(seq) for seq in input_sequences)
input_sequences = pad_sequences(input_sequences, maxlen=max_seq_len, padding='pre')

X = input_sequences[:, :-1]
y = input_sequences[:, -1]
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

# Build LSTM model
lstm_model = Sequential([
    Embedding(total_words, 64, input_length=max_seq_len-1),
    LSTM(100),
    Dense(total_words, activation='softmax')
])

lstm_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train
lstm_model.fit(X, y, epochs=100, verbose=1)

# Generate text
def generate_lstm(seed_text, next_words=10):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_seq_len-1, padding='pre')
        predicted = np.argmax(lstm_model.predict(token_list, verbose=0))

        for word, index in tokenizer.word_index.items():
            if index == predicted:
                seed_text += " " + word
                break
    return seed_text

print("\n🔹 LSTM Output:")
print(generate_lstm("deep learning", 10))


# ===============================
# 🔹 PART 2: TRANSFORMER MODEL
# ===============================

# Prepare data
words = data.split()
vocab = list(set(words))
word2idx = {w:i for i,w in enumerate(vocab)}
idx2word = {i:w for w,i in word2idx.items()}

encoded = [word2idx[w] for w in words]

seq_length = 5
X_t, y_t = [], []

for i in range(len(encoded) - seq_length):
    X_t.append(encoded[i:i+seq_length])
    y_t.append(encoded[i+seq_length])

X_t = torch.tensor(X_t)
y_t = torch.tensor(y_t)

# Transformer model
class TransformerModel(nn.Module):
    def __init__(self, vocab_size, embed_size=64, heads=2, layers=2):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_size)
        self.pos_encoding = nn.Parameter(torch.randn(1, 100, embed_size))

        encoder_layer = nn.TransformerEncoderLayer(d_model=embed_size, nhead=heads)
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=layers)

        self.fc = nn.Linear(embed_size, vocab_size)

    def forward(self, x):
        x = self.embedding(x) + self.pos_encoding[:, :x.size(1), :]
        x = self.transformer(x)
        x = self.fc(x[:, -1, :])
        return x

model = TransformerModel(len(vocab))
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# Train Transformer
for epoch in range(100):
    optimizer.zero_grad()
    output = model(X_t)
    loss = criterion(output, y_t)
    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# Generate text
def generate_transformer(seed, length=10):
    model.eval()
    result = seed.copy()

    for _ in range(length):
        inp = torch.tensor([result[-seq_length:]])
        out = model(inp)
        pred = torch.argmax(out).item()
        result.append(pred)

    return " ".join(idx2word[i] for i in result)

print("\n🔹 Transformer Output:")
seed = encoded[:5]
print(generate_transformer(seed, 10))